### ISSUE TITLE
Fibonacci CBL example not working (Version compatiblity?)

### ISSUE THREAD

**Issue by tprk77** [simon816/Command-Block-Assembly#15]
First off, this is a very cool project.

I'm test out the Fibonacci CBL example, and it doesn't seem to be working. I've two methods of generating the datapack:

1. `python3 mcc.py examples/fib.asm examples/fib.dpd` and...
2. `https://www.simon816.com/minecraft/assembler/`

With both of those datapacks, there's no output.

I'm trying to use it with Minecraft 1.14.4. Maybe that's not a supported version of Minecraft? I looked through the README, but I didn't see anything about version compatibility.

**Comment by simon816** [comment]
It should work, are you running the command? It should be `/function fib:main` or `/function fib:sub_main` (`sub_` is prefixed in the assembler, and by extension the C compiler)

**Comment by tprk77** [comment]
Yep, that was definitely the problem! Sorry, I was mistakenly expecting the setup function to just start printing the sequence. I might have figured that out, but I'm not so familiar with Minecraft commands yet. Thanks!
