### ISSUE TITLE
Computing Coordinates

### ISSUE THREAD

**Issue by Loumardes** [simon816/Command-Block-Assembly#5]
You can convert coordinates to scoreboard values and scoreboard values to coordinates in Minecraft :

    To scoreboard :
_execute as @e store result score @s Xcoordinates run data get entity @s Pos[0] 1_

    To coordinates :
_execute store result entity @e[tag=memory_entity,limit=1] Pos[0] double 1 run scoreboard players get @s Xcoordinates_ 

In NBT format :
_Pos[0]_ : X
_Pos[1]_ : Y
_Pos[2]_ : Z

Same with rotation in degrés : 
_Rotation[0]_ : player course
_Rotation[1]_ : inclination

I think assembly instructions may be useful
Hope it will help

**Comment by simon816** [comment]
This is something I've been meaning to do. It's only been possible since 1.13, the old way I set a position was to `tp` in a loop that shifted the entity.

**Comment by simon816** [comment]
This is being implemented in my new language called CBL:
https://github.com/simon816/Command-Block-Assembly/blob/1e30140344ae91e6952c3543606794791d1a658e/cbl/entity_support.py#L86-L214

It's still in early development but it will work something like this:
```
entity.pos = (10, 10, 10);
entity.pos.x += some_value;
entity1.pos = entity2.pos;
```

**Comment by FinnT730** [comment]
looks amazing!
Don't know where else to put this, but this is one of the better tools for something like this out there!
Thanks for making it, and I hope you will continue with it!
