### ISSUE TITLE
Potential feature: Dynamic dispatch without a tick delay

### ISSUE THREAD

**Issue by sarahzrf** [simon816/Command-Block-Assembly#7]
A series of chain command blocks that loops back on itself (most compactly, just two facing each other) will continue to run to the chain limit if both have the tag `UpdateLastExecution` set to `0`. This allows dynamic dispatch to be done without a tick delay by updating one of the command blocks in such a chain while a previous one is executing, which seems like a potentially desirable feature.

**Comment by simon816** [comment]
I'll check it out. I was under the impression that command blocks only triggered once per tick.

Another strategy for dynamic dispatch is to create a lookup table and give each function an ID. This was what I previously did (see [`add_lookup_table`](https://github.com/simon816/Command-Block-Assembly/blob/ffc8d1780dc1ffb9f12522d2774dfcf884383d01/assembler.py#L845) and [`function_id`](https://github.com/simon816/Command-Block-Assembly/blob/ffc8d1780dc1ffb9f12522d2774dfcf884383d01/assembler.py#L155)) maybe I could add that as an option too.

**Comment by sarahzrf** [comment]
They do, *if* `UpdateLastExecution` is set to `1`, which is the default and cannot be changed directly in the UI.

**Comment by simon816** [comment]
I've implemented this at a low level, and exposed it in [Command IR](https://github.com/simon816/Command-Block-Assembly/wiki/Command-IR) with these instructions:

### clear_zero_tick
`clear_zero_tick`

Remove any function from the special zero-tick command block and clear
    the zero-tick flag.


***
### set_zero_tick_from_stack
`set_zero_tick_from_stack`

Sets the special zero-tick command block to execute the function
    at the top of the global stack. The function will execute in the same
    tick once control is returned to the command block.


***
### zero_tick_set
`zero_tick_set <ref>`

Sets the special zero-tick command block to the given function
    or function reference. The function will execute in the same tick once
    control is returned to the command block.

**ref**: `(Variable|FunctionLike)` Function reference

**Comment by sarahzrf** [comment]
cool :)
