### ISSUE TITLE
Could i read a tag from entity or an other way of storing other types than int (This case string)

### ISSUE THREAD

**Issue by artemking4** [simon816/Command-Block-Assembly#8]
Could i read a tag from entity and store it in a var? Or an other way of storing string somewhere?

**Comment by simon816** [comment]
Strings are quite limited using the techniques we have for using them. It should be possible to use NBT to store and retrieve strings. However I am unaware of a technique to manipulate them (e.g. append string). Using Command IR this should be possible - https://github.com/simon816/Command-Block-Assembly/wiki/Command-IR-Instruction-Reference#nbt-instructions
In the assembly language / C compiler there isn't explicit support, but you can construct a [`/data`](https://minecraft.gamepedia.com/Commands/data) command to store/retrieve strings

**Comment by artemking4** [comment]
Thank you much for the info.
